language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_install:
  - if [ `uname` = "Linux" ]; then export CXX=g++-4.9; fi

install:
  - npm install
